//! User-visible commands against real files/processes. No mocked provider or billing data.
use nyrva_core::{cli, parse_statusline, History, Provider};
use serde_json::{json, Value};
use std::{fs, io::{Read, Write}, net::TcpStream, path::{Path, PathBuf}, process::{Command, Stdio}, sync::atomic::{AtomicU64, Ordering}, thread, time::{Duration, Instant}};
static NEXT: AtomicU64 = AtomicU64::new(0);
struct Temp(PathBuf);
impl Temp { fn new() -> Self { let p = std::env::temp_dir().join(format!("nyrva-everywhere-{}-{}-{}",std::process::id(),cli::now_ms(),NEXT.fetch_add(1,Ordering::Relaxed))); fs::create_dir_all(&p).unwrap(); Self(p) } }
impl Drop for Temp { fn drop(&mut self) { let _ = fs::remove_dir_all(&self.0); } }
fn call(root:&Path,args:&[&str],v:Value)->Result<Value,String> { let mut out=Vec::new(); let raw=v.to_string(); cli::run(&args.iter().map(|s|s.to_string()).collect::<Vec<_>>(),root,&mut raw.as_bytes(),&mut out)?; serde_json::from_slice(&out).map_err(|_| "expected versioned JSON".into()) }
fn good(root:&Path,args:&[&str],v:Value)->Value { let r=call(root,args,v); assert!(r.is_ok(),"{args:?}: {r:?}"); r.unwrap() }
fn prefs(root:&Path)->Value { good(root,&["settings","export","--json"],Value::Null)["settings"].clone() }
fn seed(root:&Path) { let s=parse_statusline(Provider::Antigravity,"active",r#"{"quota":{"weekly":{"remaining_fraction":0.07,"reset_in_seconds":3600}},"session_id":"private-session","workspace":{"project_dir":"/private/customer/project"},"model":{"id":"private-model"}}"#,cli::now_ms()).unwrap(); History::open(&cli::database_path(root)).unwrap().record(&s).unwrap(); }
#[test]
fn settings_rollback_is_explicit_and_recovers_previous_valid_preferences() { let t=Temp::new(); let mut p=prefs(&t.0); p["layout"]=json!("bars"); good(&t.0,&["settings","import","--apply"],p); let mut next=prefs(&t.0); next["layout"]=json!("reset-first"); good(&t.0,&["settings","import","--apply"],next); assert!(call(&t.0,&["settings","rollback"],Value::Null).is_err()); good(&t.0,&["settings","rollback","--apply"],Value::Null); assert_eq!(prefs(&t.0)["layout"],"bars"); }
#[test]
fn settings_reject_nested_unknowns_and_bad_thresholds_without_mutation() { let t=Temp::new(); let initial=prefs(&t.0); let mut bad=initial.clone(); bad["providers"]["credentials"]=json!("SECRET"); assert!(call(&t.0,&["settings","import","--apply"],bad).is_err()); let mut bad=initial.clone(); bad["alerts"]["thresholds"]=json!([1.5]); assert!(call(&t.0,&["settings","import","--apply"],bad).is_err()); assert_eq!(prefs(&t.0),initial); }
#[test]
fn diagnostic_export_is_allowlisted_not_a_database_dump() { let t=Temp::new(); seed(&t.0); fs::write(t.0.join("credentials.json"),"SECRET-TOKEN").unwrap(); let d=good(&t.0,&["export","--json"],Value::Null); assert_eq!(d["schema_version"],1); let s=d.to_string(); for secret in ["SECRET-TOKEN","private-session","private-model","/private",t.0.to_str().unwrap()] { assert!(!s.contains(secret),"diagnostics leaked forbidden metadata"); } }
#[test]
fn doctor_and_redirected_top_are_readonly_and_versioned() { let t=Temp::new(); for args in [&["doctor","--json"][..],&["top","--once","--json"][..]] { let d=good(&t.0,args,Value::Null); assert_eq!(d["schema_version"],1); assert!(!d.to_string().contains('\u{1b}')); } assert!(!cli::database_path(&t.0).exists()); assert!(call(&t.0,&["top","--interval","0"],Value::Null).is_err()); }
#[test]
fn simultaneous_alert_refreshes_emit_each_window_threshold_only_once() { let t=Temp::new(); seed(&t.0); let workers=(0..6).map(|_|{let root=t.0.clone(); thread::spawn(move||call(&root,&["alerts","refresh","--json"],Value::Null))}).collect::<Vec<_>>(); let mut keys=std::collections::HashSet::new(); for worker in workers { let r=worker.join().unwrap(); assert!(r.is_ok(),"{r:?}"); for a in r.unwrap()["new_alerts"].as_array().unwrap() { assert!(keys.insert(a["id"].to_string()),"duplicate alert emitted across processes/connections"); } } assert!(!keys.is_empty()); }
#[test]
fn integration_is_opt_in_and_restores_only_its_owned_field() { let t=Temp::new(); let home=t.0.join("home"); let path=home.join(".gemini/antigravity-cli/settings.json"); fs::create_dir_all(path.parent().unwrap()).unwrap(); fs::write(&path,r#"{"theme":"old","statusLine":{"type":"command","command":"echo existing"},"auth":{"untouched":"SECRET"}}"#).unwrap(); let home=home.to_str().unwrap(); let exe=env!("CARGO_BIN_EXE_nyrva-telemetry"); let args=["integrations","plan","antigravity","--home",home,"--executable",exe,"--json"]; let plan=good(&t.0,&args,Value::Null); assert_eq!(plan["requires_confirmation"],true); assert!(!plan.to_string().contains("SECRET")); let original=fs::read(&path).unwrap(); assert!(call(&t.0,&["integrations","install","antigravity","--home",home,"--executable",exe],Value::Null).is_err()); assert_eq!(fs::read(&path).unwrap(),original); assert!(call(&t.0,&["integrations","install","antigravity","--home",home,"--executable",exe,"--apply"],Value::Null).is_err()); good(&t.0,&["integrations","install","antigravity","--home",home,"--executable",exe,"--apply","--replace"],Value::Null); let mut current:Value=serde_json::from_slice(&fs::read(&path).unwrap()).unwrap(); assert_ne!(current["statusLine"]["command"],"echo existing"); current["theme"]=json!("edited-after-install"); fs::write(&path,serde_json::to_vec(&current).unwrap()).unwrap(); good(&t.0,&["integrations","remove","antigravity","--home",home,"--apply"],Value::Null); let restored:Value=serde_json::from_slice(&fs::read(&path).unwrap()).unwrap(); assert_eq!(restored["statusLine"]["command"],"echo existing"); assert_eq!(restored["theme"],"edited-after-install"); assert_eq!(restored["auth"]["untouched"],"SECRET"); }
#[test]
fn integration_refuses_to_overwrite_a_statusline_changed_after_install() { let t=Temp::new(); let home=t.0.join("home"); let h=home.to_str().unwrap(); good(&t.0,&["integrations","install","claude","--home",h,"--executable",env!("CARGO_BIN_EXE_nyrva-telemetry"),"--apply"],Value::Null); let path=home.join(".claude/settings.json"); let mut v:Value=serde_json::from_slice(&fs::read(&path).unwrap()).unwrap(); v["statusLine"]=json!({"type":"command","command":"echo newer-user-choice"}); fs::write(&path,serde_json::to_vec(&v).unwrap()).unwrap(); let before=fs::read(&path).unwrap(); assert!(call(&t.0,&["integrations","remove","claude","--home",h,"--apply"],Value::Null).is_err()); assert_eq!(fs::read(&path).unwrap(),before); }
#[test]
fn integration_does_not_invent_codex_statusline_support() { let t=Temp::new(); assert!(call(&t.0,&["integrations","install","codex","--apply"],Value::Null).is_err()); }
#[cfg(unix)]
#[test]
fn preferences_never_follow_a_symlink_to_another_file() { use std::os::unix::fs::symlink; let t=Temp::new(); let p=prefs(&t.0); let target=t.0.join("provider-auth.json"); fs::write(&target,"secret-auth").unwrap(); fs::create_dir_all(t.0.join("telemetry")).unwrap(); symlink(&target,t.0.join("telemetry/preferences.json")).unwrap(); assert!(call(&t.0,&["settings","import","--apply"],p).is_err()); assert_eq!(fs::read_to_string(target).unwrap(),"secret-auth"); }
fn http(address:&str,request:&str)->String { let mut s=TcpStream::connect(address).unwrap(); s.set_read_timeout(Some(Duration::from_secs(3))).unwrap(); s.write_all(request.as_bytes()).unwrap(); let mut out=String::new(); s.read_to_string(&mut out).unwrap(); out }
struct Child(std::process::Child);
impl Drop for Child { fn drop(&mut self) { let _=self.0.kill(); let _=self.0.wait(); } }
#[test]
fn local_api_requires_session_auth_has_no_cors_and_rejects_writes() { let t=Temp::new(); seed(&t.0); let mut child=Child(Command::new(env!("CARGO_BIN_EXE_nyrva-telemetry")).env("NYRVA_DATA_DIR",&t.0).args(["serve","--port","0","--duration","10"]).stdin(Stdio::null()).stdout(Stdio::null()).stderr(Stdio::null()).spawn().unwrap()); let path=t.0.join("telemetry/api-session.json"); let until=Instant::now()+Duration::from_secs(5); while !path.exists() && Instant::now()<until { assert!(child.0.try_wait().unwrap().is_none(),"serve exited before creating a session"); thread::sleep(Duration::from_millis(25)); } assert!(path.exists(),"serve did not create a private session file"); let session:Value=serde_json::from_slice(&fs::read(&path).unwrap()).unwrap(); let address=session["address"].as_str().unwrap(); let token=session["token"].as_str().unwrap(); assert!(address.starts_with("127.0.0.1:")); assert!(token.len()>=64); let unauth=http(address,&format!("GET /v1/status HTTP/1.1\r\nHost: {address}\r\n\r\n")); assert!(unauth.starts_with("HTTP/1.1 401")); let response=http(address,&format!("GET /v1/status HTTP/1.1\r\nHost: {address}\r\nAuthorization: Bearer {token}\r\n\r\n")); assert!(response.starts_with("HTTP/1.1 200"),"{response}"); assert!(!response.to_ascii_lowercase().contains("access-control-allow-origin")); assert!(!response.contains(token)); let body=response.split("\r\n\r\n").nth(1).unwrap(); assert_eq!(serde_json::from_str::<Value>(body).unwrap()["schema_version"],1); let forbidden=http(address,&format!("POST /v1/status HTTP/1.1\r\nHost: {address}\r\nAuthorization: Bearer {token}\r\n\r\n")); assert!(forbidden.starts_with("HTTP/1.1 405")); let origin=http(address,&format!("GET /v1/status HTTP/1.1\r\nHost: {address}\r\nAuthorization: Bearer {token}\r\nOrigin: https://evil.example\r\n\r\n")); assert!(origin.starts_with("HTTP/1.1 403")); }
